name: Validar HTML

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4
        
      - name: Convert ASPX to HTML for validation
        run: |
          find . -name "*.aspx" -exec bash -c 'cp "$0" "${0%.aspx}.html"' {} \;
          
      - name: Validar HTML
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: .

      - name: Mensaje confirmacion
        run: echo Pipeline_validacion_HTML_correcta